// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP3.Data;

#nullable disable

namespace TP3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250409034847_UtilisateurFakerMigration")]
    partial class UtilisateurFakerMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP3.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Courriel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("InfoLettre")
                        .HasColumnType("bit");

                    b.Property<string>("MotDePasseActuel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pseudonyme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Courriel = "Annabelle.Bernier50@gmail.com",
                            InfoLettre = false,
                            MotDePasseActuel = "D4f2tqBRBc",
                            Nom = "Bernier",
                            Prenom = "Annabelle",
                            Pseudonyme = "Annabelle_Bernier79"
                        },
                        new
                        {
                            Id = 2,
                            Courriel = "Kraig51@hotmail.com",
                            InfoLettre = true,
                            MotDePasseActuel = "N8iMJNcJ9C",
                            Nom = "Mraz",
                            Prenom = "Kraig",
                            Pseudonyme = "Kraig_Mraz39"
                        },
                        new
                        {
                            Id = 3,
                            InfoLettre = false,
                            MotDePasseActuel = "x0GmrehBfc",
                            Nom = "Dare",
                            Prenom = "Royce",
                            Pseudonyme = "Royce_Dare61"
                        },
                        new
                        {
                            Id = 4,
                            Courriel = "Icie28@gmail.com",
                            InfoLettre = true,
                            MotDePasseActuel = "7sVSYiKcxT",
                            Nom = "Hirthe",
                            Prenom = "Icie",
                            Pseudonyme = "Icie_Hirthe"
                        },
                        new
                        {
                            Id = 5,
                            Courriel = "Donato.Huel@yahoo.com",
                            InfoLettre = true,
                            MotDePasseActuel = "mx0pCw4pkG",
                            Nom = "Huel",
                            Prenom = "Donato",
                            Pseudonyme = "Donato11"
                        },
                        new
                        {
                            Id = 6,
                            Courriel = "Nelle16@hotmail.com",
                            InfoLettre = true,
                            MotDePasseActuel = "ASZKqZkhH_",
                            Nom = "Fritsch",
                            Prenom = "Nelle",
                            Pseudonyme = "Nelle.Fritsch5"
                        },
                        new
                        {
                            Id = 7,
                            Courriel = "Skyla_Prosacco34@yahoo.com",
                            InfoLettre = false,
                            MotDePasseActuel = "JocBVBPiOo",
                            Nom = "Prosacco",
                            Prenom = "Skyla",
                            Pseudonyme = "Skyla7"
                        },
                        new
                        {
                            Id = 8,
                            Courriel = "Dora36@yahoo.com",
                            InfoLettre = true,
                            MotDePasseActuel = "fqT2Zsq7nl",
                            Nom = "Bailey",
                            Prenom = "Dora",
                            Pseudonyme = "Dora_Bailey"
                        },
                        new
                        {
                            Id = 9,
                            Courriel = "Susie76@gmail.com",
                            InfoLettre = true,
                            MotDePasseActuel = "8ttZ6FFgBz",
                            Nom = "Fahey",
                            Prenom = "Susie",
                            Pseudonyme = "Susie89"
                        },
                        new
                        {
                            Id = 10,
                            Courriel = "Aurelio_Stokes@yahoo.com",
                            InfoLettre = false,
                            MotDePasseActuel = "XZJOn7qxzJ",
                            Nom = "Stokes",
                            Prenom = "Aurelio",
                            Pseudonyme = "Aurelio_Stokes16"
                        },
                        new
                        {
                            Id = 11,
                            Courriel = "Jayda6@yahoo.com",
                            InfoLettre = true,
                            MotDePasseActuel = "D_BbzRb6tt",
                            Nom = "Koelpin",
                            Prenom = "Jayda",
                            Pseudonyme = "Jayda79"
                        },
                        new
                        {
                            Id = 12,
                            Courriel = "Stacey4@yahoo.com",
                            InfoLettre = true,
                            MotDePasseActuel = "03VN9XvE3O",
                            Nom = "Ebert",
                            Prenom = "Stacey",
                            Pseudonyme = "Stacey.Ebert98"
                        },
                        new
                        {
                            Id = 13,
                            InfoLettre = false,
                            MotDePasseActuel = "CM1jPjgZsV",
                            Nom = "Shanahan",
                            Prenom = "Jimmie",
                            Pseudonyme = "Jimmie.Shanahan57"
                        },
                        new
                        {
                            Id = 14,
                            Courriel = "Trinity93@hotmail.com",
                            InfoLettre = true,
                            MotDePasseActuel = "jxdtQMsCdp",
                            Nom = "Kub",
                            Prenom = "Trinity",
                            Pseudonyme = "Trinity_Kub27"
                        },
                        new
                        {
                            Id = 15,
                            InfoLettre = false,
                            MotDePasseActuel = "S2foRl8srp",
                            Nom = "Pfannerstill",
                            Prenom = "Carrie",
                            Pseudonyme = "Carrie.Pfannerstill"
                        },
                        new
                        {
                            Id = 16,
                            InfoLettre = false,
                            MotDePasseActuel = "udFa0aJ5rO",
                            Nom = "Feest",
                            Prenom = "Lelia",
                            Pseudonyme = "Lelia65"
                        },
                        new
                        {
                            Id = 17,
                            Courriel = "Kiara84@gmail.com",
                            InfoLettre = true,
                            MotDePasseActuel = "sEYZId4_pg",
                            Nom = "Ruecker",
                            Prenom = "Kiara",
                            Pseudonyme = "Kiara.Ruecker97"
                        },
                        new
                        {
                            Id = 18,
                            Courriel = "Nicholaus24@yahoo.com",
                            InfoLettre = false,
                            MotDePasseActuel = "jgl9QGdRU8",
                            Nom = "Ratke",
                            Prenom = "Nicholaus",
                            Pseudonyme = "Nicholaus_Ratke"
                        },
                        new
                        {
                            Id = 19,
                            Courriel = "Ed.Emmerich@hotmail.com",
                            InfoLettre = false,
                            MotDePasseActuel = "X_KjKDC8vE",
                            Nom = "Emmerich",
                            Prenom = "Ed",
                            Pseudonyme = "Ed.Emmerich28"
                        },
                        new
                        {
                            Id = 20,
                            Courriel = "Bernard86@hotmail.com",
                            InfoLettre = true,
                            MotDePasseActuel = "O38d7IS3ZI",
                            Nom = "Hilpert",
                            Prenom = "Bernard",
                            Pseudonyme = "Bernard90"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
